tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/drivers"
tap "caskroom/fonts"
tap "caskroom/cask"
brew "heroku"
brew "hub"
brew "libxslt"
brew "mas"
brew "nginx"
brew "nmap"
brew "postgresql"
brew "rbenv"
brew "redis"
brew "rmtrash"
brew "siege"
brew "sloccount"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "zsh-syntax-highlighting"
cask "adobe-digital-editions"
cask "alfred"
cask "blender"
cask "calibre"
cask "cyberduck"
cask "dash"
cask "deluge"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "handbrake"
cask "imageoptim"
cask "karabiner-elements"
cask "macdown"
cask "ngrok"
cask "phoenix"
cask "postico"
cask "sip"
cask "sketch"
cask "slack"
cask "sourcetree"
cask "transmit"
cask "tunnelblick"
cask "unrarx"
cask "visual-studio-code"
cask "webstorm"
cask "zoomus"
cask "caskroom/drivers/logitech-options"
mas "Affinity Photo", id: 824183456
mas "Airmail 3", id: 918858936
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iOrdning", id: 1157906903
mas "Keynote", id: 409183694
mas "Microsoft OneNote", id: 784801555
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Twitter", id: 409789998
